Prepared release 0.1.0
exasol/script-languages-developer-sandbox pull request #59
Opened 2022-10-05 16:46 UTC by tomuben

2022-10-05 18:28 UTC, tkilias requested changes

2022-10-05 18:28 UTC, tkilias commented on doc/changes/changes_0.1.0.md
> +# script-languages-container-ci-setup 0.1.0, released 2022-10-06
```suggestion
# script-languages-developer-sandbox 0.1.0, released 2022-10-06
```

2022-10-05 18:28 UTC, tkilias commented on doc/changes/changes_0.1.0.md
> +Initial release of script-languages-container-ci-setup. Provides the creation of a developer sandbox AMI and virtual machine images for a specific version of the script-languages-release project.
```suggestion
Initial release of the script-languages-developer-sandbox. It provides the creation of a developer sandbox AMI and virtual machine images for a specific version of the script-languages-release project.
```

2022-10-06 09:37 UTC, tomuben commented on doc/changes/changes_0.1.0.md
> +# script-languages-container-ci-setup 0.1.0, released 2022-10-06
fixed

2022-10-06 09:37 UTC, tomuben commented on doc/changes/changes_0.1.0.md
> +Initial release of script-languages-container-ci-setup. Provides the creation of a developer sandbox AMI and virtual machine images for a specific version of the script-languages-release project.
integrated

2022-10-06 09:38 UTC, tkilias approved these changes

2022-10-06 09:54 UTC, merged